FROM java:8
VOLUME /tmp/tomcat
ADD springboot-demo-boot-0.0.1-SNAPSHOT.jar springboot-docker.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/springboot-docker.jar"]

# FROM：指定存在的镜像，java:8是我刚刚拉取的镜像，运行的基础。
# VOLUME：指向的一个临时文件，用于存储tomcat工作。
# ADD：复制文件并且重命名文件。ENTRYPOINT：初始化配置或者自定义配置。